package POJOs;
// Generated 28/08/2023 06:27:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private Cliente cliente;
     private FormaPago formaPago;
     private Usuario usuarioByUsuarioModifica;
     private Usuario usuarioByUsuarioIngreso;
     private Boolean estado;
     private Date fechaVenta;
     private Boolean estadoFinalizado;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Set<VentaDetalle> ventaDetalles = new HashSet<VentaDetalle>(0);

    public Venta() {
    }

    public Venta(Cliente cliente, FormaPago formaPago, Usuario usuarioByUsuarioModifica, Usuario usuarioByUsuarioIngreso, Boolean estado, Date fechaVenta, Boolean estadoFinalizado, Date fechaIngreso, Date fechaModifica, Set<VentaDetalle> ventaDetalles) {
       this.cliente = cliente;
       this.formaPago = formaPago;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.estado = estado;
       this.fechaVenta = fechaVenta;
       this.estadoFinalizado = estadoFinalizado;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.ventaDetalles = ventaDetalles;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Boolean getEstadoFinalizado() {
        return this.estadoFinalizado;
    }
    
    public void setEstadoFinalizado(Boolean estadoFinalizado) {
        this.estadoFinalizado = estadoFinalizado;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set<VentaDetalle> getVentaDetalles() {
        return this.ventaDetalles;
    }
    
    public void setVentaDetalles(Set<VentaDetalle> ventaDetalles) {
        this.ventaDetalles = ventaDetalles;
    }




}


